### ISSUE TITLE
这是我的版权，其它人转发均为盗版！

### ISSUE THREAD

**Issue by sdlddr** [huangjunse/GooFlow#1]
这是我的版权，其它人转发均为盗版！

**Comment by huangjunsen** [comment]
抱歉，比较少上github，现在才看到。

你这话就说得有失偏颇了。
首先，你没有在你首发的论坛上注明这个工程的版权协议。
然后，你的代码中也不存在任何开源协议。
再者，我的工程里面注明了GPL的协议的。
最后，我在代码里面也详细注释了该工程并非我原创。
url: https://github.com/huangjunsen/GooFlow/blob/master/dist/GooFlow.js
为什么你要用这么难看的字眼来批判开源的精神？

而且，退一万步讲，即使我上面的这些事情都没有做，没有设置开源协议，没有代码注释，你也无权认定我为盗版。

**Comment by sdlddr** [comment]
我一年前都已经看懂版权协议了，现在你才来回复。。。。。。

**Comment by huangjunsen** [comment]
何谓看懂？
你并不在意在别人的issue里面留下难看的字眼，but我在意。
因为工作的关系，很长一段时间我都不允许登录这里，所以现在才来回复。

**Comment by justjavac** [comment]
当作者没有写开源协议时，说明作者保留了所有的权利，那么在使用时应该征得原作者的许可放可做二次分发。

把别人的作品拿来然后自己以 GPL 协议发布，这个就是侵权行为了。

**Comment by justjavac** [comment]
@huangjunsen 

> 退一万步讲，即使我上面的这些事情都没有做，没有设置开源协议，没有代码注释，你也无权认定我为盗版。

一个很简单的道理：就算你不知道这个软件是谁开发的，难道你还不知道这个软件是不是你开发的吗。既然不是你的，那么你也发布软件的衍生作品时就应该取得原作者的许可。

虽然我在另一个 issue 里面批判原作者私藏挖矿代码的行为，但是在这个 issue 下，sdlddr 是对的，而你(huangjunsen)是一个侵权者。

**Comment by Jinxiansen** [comment]
@justjavac     那你怕是得看看 https://github.com/sdlddr/Gooflow/issues/12 

了解一下楼主是什么样的人。

**Comment by justjavac** [comment]
@Jinxiansen 我看的比你多，但是咱们**对事不对人**。就算楼主十恶不赦，那这个软件的原作者也是他。

**Comment by shamiao** [comment]
@justjavac 我真希望有壮士能直接fork掉 @sdlddr 开源的 1.7.3 release 。

这个release是“双授权”的：两个授权文件，一份无修改MIT，一份自定义协议。照 MIT 走，搞定。

**Comment by justjavac** [comment]
@shamiao  那就看这个项目没有没那么大的价值了

**Comment by Jinxiansen** [comment]
🙄🙄🙄 真刺激！

**Comment by namoen0301** [comment]
这个 fork 过来的项目是否需要保留 MIT License 文本？

**Comment by justjavac** [comment]
@wbsdty331 这个项目不是 fork 的，而且这个 repo 的创建时间比原作者的要早 1~2 年吧

**Comment by samchenws** [comment]
我觉得sdlddr 不厚道@sdlddr 先不说挖矿的事情,就@huangjunsen 建的这个来说，
@sdlddr你为什么不早几年来说了？意图何在了？？@huangjunsen 要么把Gooflow推翻掉，自己重新写吧,
@sdlddr @huangjunsen 要么2人合作共同维护
这事我更支持 huangjunsen

**Comment by sdlddr** [comment]
@samchenws 何时发现何时来说，有什么问题？？？
该衍生版本很原始，我之前早就允许 huangjunsen 继续以GPL协议发布此版本了。

**Comment by liuziangexit** [comment]
两个极品

**Comment by huangjunsen** [comment]
各位大神，先说一个底线： 这里不是谩骂场所。

    话说，不常上github，我任职的企业，也严禁将我在司期间写的代码上传到github，所以这个项目我已经有过好几个版本的改动，但是并没有上传上来。

    至于开源协议，先说说我为什么会选择GPL而不是MIT。

    据我个人理解，GPL相对于MIT更具有“开源”的精神，使用者必须开源，而且使用了该项目的衍生项目也必须开源；而MIT却不是，随时都可以将该项目用在闭源项目中，这样对期望通过该项目引发思考的其他同学是不友好的。

    这个项目，初衷是提供给前端爱好者一个学习的地方，并非商用；如果想要商用，或者在版权敏感的项目中使用，则请自觉自行开发一套这样的程序。

    这里对开源协议的理解不知道是否有误，欢迎指正。

    @justjavac 这里有一个情况，或许大家都没有了解到，在我代码中注明的源代码出处的论坛中（http://www.iteye.com/topic/1135092），作者说该代码只要不商用就没有问题，而且在论坛的讨论中，作者明确表示了“非盈利时采用GPL协议”。

    首先，当年（15年的时候）我并不100%确认论坛中发布的人就是原作者，所以从来没有咨询/询问过该源码的出处、版权问题；然后，我在源码中，详细记录了该项目的出处，以及说明了该源码并非我个人创作这些情况；最后，GPL协议，并没有要求要提供原作者信息。

    至于孰是孰非，这里并不是要讨论一个结果。我尊重尊敬为社区贡献力量的人，给迷茫的前端er提供了进修学习的场所和地方。如果觉得我的做法不妥当的，欢迎批评，不过希望能提供整改的方案和意见。

    最后，各位如果对这份代码有兴趣，希望完善这份代码的同学，欢迎和我联系。

--------
顺便吐槽一下github issues评论的换行方式，好挫……
