### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by xdwxls** [huangjunse/GooFlow#2]
你好，用你的代码开发，基于画线的部分，我想from 和 to 指向的是一个节点，也就是自己指向自己，这功能目前没有，应该如何改造实现呢？

**Comment by huangjunsen** [comment]
抱歉，比较少上github。
关于你说的功能，提供一个实现思路给你：
1. from/to的数据并没有限制不能为相同，因此，从数据写入的层面上，是可以相同的，这一点无需改造。
2. 要指向自己，需要画一个有缺口的圆，末端加上箭头。
3. 上面准备好之后，在图上添加一个右键功能，命名如：“自循环”之类。
4. 对这个功能进行二次开发扩展即可。

因为最近都在搞后端的开发，所以js类的插件应该短期内不会进行更新。
有问题可以继续问。
